### ISSUE TITLE
[Question] Any suggested linker and toolchain? Any example?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [ncb85/SmallC-85#5]
Is this compiler used inside any tool-chain? Any example of a project that uses it to build a runnable binary?
Is it usable with ACK tools (Amsterdam compiler for I8080 and other CPUs)?
Which linkers, which assemblers can be used?
Has it be used to build Cp/m-80 binaries or other 8080/8085-based systems?

**Comment by ncb85** [comment]
Yes, I am using it from Netbeans IDE to produce CP/M binaries, with one click. Have a look at hello world example here:
https://github.com/ncb85/utilis-and-examples/tree/master/cpm_hello
There is also a makefile provided in the example.

This compiler produces ASM source for ASxxxx Cross Assemblers. 
Your last question: no, it has not be used to build CP/M binaries, but it can be. CP/M have had historically many many different compilers, assemblers and tool chains.
