### ISSUE TITLE
Known issue:  Lots of compiler warnings. I propose a solution.

### ISSUE THREAD

**Issue by poetnerd** [ncb85/SmallC-85#7]
It is well known that SmallC throws up a lot of compiler warnings.  Root cause is the wide and diverse
couplings and dependencies among the modules.

I've made changes in my own fork that silences the warnings that Mac clang raises. (The fork is still local. I'll be pushing it to github very It required touching every source file, and creating a new include file extern.h that allows all the modules to
see clean forward declarations of all the procedures they need.

Before I make a pull request that touches every file in the tree, I figured I should open an Issue to discuss.

Feel free to review code in my fork.

**Comment by ncb85** [comment]
Actually I did not have any warnings at all on gcc compiler. What is the compiler you are using?

**Comment by poetnerd** [comment]
I’m using Mac clang.

**Comment by ncb85** [comment]
C89 permits the type to be omitted, with int assumed. 
Running Clang with "clang -std=c89" might have solved the warnings, do not know for sure.
